use super::super::{ExecutorAvailability, ExecutorDefinition};
use super::matchers::*;
use crate::api::plan::{
    CONTROL_IF_CAPABILITY, CONTROL_MERGE_CAPABILITY, CONTROL_SPLIT_CAPABILITY,
    CONTROL_SWITCH_CAPABILITY, DataPolicy, ExecutionRecipe, JSON_EXTRACT_CAPABILITY,
    LLM_CLASSIFY_CAPABILITY, LLM_STRUCTURED_OUTPUT_CAPABILITY, MODEL_LOCK_CHECK_CAPABILITY,
    MODEL_SELECT_CAPABILITY,
};

pub(super) static CONTROL_MODEL_RESERVED_EXECUTORS: [ExecutorDefinition; 11] = [
    ExecutorDefinition {
        id: "builtin.json.extract.v1",
        kind: "builtin",
        capabilities: &[JSON_EXTRACT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::JsonExtract,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.extract_json_path", JSON_EXTRACT_CAPABILITY)],
        plans_models: false,
        matcher: matches_json_extract,
    },
    ExecutorDefinition {
        id: "builtin.control.if.v1",
        kind: "builtin",
        capabilities: &[CONTROL_IF_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ControlIf,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.if_value", CONTROL_IF_CAPABILITY)],
        plans_models: false,
        matcher: matches_control_if,
    },
    ExecutorDefinition {
        id: "builtin.control.switch.v1",
        kind: "builtin",
        capabilities: &[CONTROL_SWITCH_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ControlSwitch,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.switch_value", CONTROL_SWITCH_CAPABILITY)],
        plans_models: false,
        matcher: matches_control_switch,
    },
    ExecutorDefinition {
        id: "builtin.control.merge.v1",
        kind: "builtin",
        capabilities: &[CONTROL_MERGE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ControlMerge,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.merge_values", CONTROL_MERGE_CAPABILITY)],
        plans_models: false,
        matcher: matches_control_merge,
    },
    ExecutorDefinition {
        id: "builtin.control.split.v1",
        kind: "builtin",
        capabilities: &[CONTROL_SPLIT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ControlSplit,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.split_value", CONTROL_SPLIT_CAPABILITY)],
        plans_models: false,
        matcher: matches_control_split,
    },
    ExecutorDefinition {
        id: "builtin.model.select.v1",
        kind: "builtin",
        capabilities: &[MODEL_SELECT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ModelSelect,
        data_policy: DataPolicy::JsonValues,
        atoms: &[(
            "lightflow.atom.select_model_variant",
            MODEL_SELECT_CAPABILITY,
        )],
        plans_models: false,
        matcher: matches_model_select,
    },
    ExecutorDefinition {
        id: "builtin.model.lock.check.v1",
        kind: "builtin",
        capabilities: &[MODEL_LOCK_CHECK_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ModelLockCheck,
        data_policy: DataPolicy::JsonValues,
        atoms: &[(
            "lightflow.atom.check_model_lock",
            MODEL_LOCK_CHECK_CAPABILITY,
        )],
        plans_models: false,
        matcher: matches_model_lock_check,
    },
    ExecutorDefinition {
        id: "builtin.llm.classify.v1",
        kind: "builtin",
        capabilities: &[LLM_CLASSIFY_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::LlmClassify,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.classify_text", LLM_CLASSIFY_CAPABILITY)],
        plans_models: false,
        matcher: matches_llm_classify,
    },
    ExecutorDefinition {
        id: "builtin.llm.structured_output.v1",
        kind: "builtin",
        capabilities: &[LLM_STRUCTURED_OUTPUT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::LlmStructuredOutput,
        data_policy: DataPolicy::JsonValues,
        atoms: &[(
            "lightflow.atom.structured_output",
            LLM_STRUCTURED_OUTPUT_CAPABILITY,
        )],
        plans_models: false,
        matcher: matches_llm_structured_output,
    },
    ExecutorDefinition {
        id: "lightflow.onnx.executor.v1",
        kind: "reserved",
        capabilities: &["lightflow.onnx"],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Unavailable,
        recipe: ExecutionRecipe::Passthrough,
        data_policy: DataPolicy::JsonValues,
        atoms: &[],
        plans_models: false,
        matcher: matches_never,
    },
    ExecutorDefinition {
        id: "lightflow.candle.executor.v1",
        kind: "reserved",
        capabilities: &["lightflow.candle"],
        features: &["gguf"],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Unavailable,
        recipe: ExecutionRecipe::Passthrough,
        data_policy: DataPolicy::JsonValues,
        atoms: &[],
        plans_models: true,
        matcher: matches_never,
    },
];
