use super::super::{ExecutorAvailability, ExecutorDefinition};
use super::matchers::*;
use crate::api::plan::{
    DataPolicy, ExecutionRecipe, IMAGE_EDIT_CAPABILITY, IMAGE_GENERATE_CAPABILITY,
    IMAGE_INPAINT_CAPABILITY, PREVIEW_EDIT_ENGINE, PREVIEW_ENGINE, PREVIEW_INPAINT_ENGINE,
};

pub(super) static CORE_PREVIEW_EXECUTORS: [ExecutorDefinition; 4] = [
    ExecutorDefinition {
        id: "passthrough",
        kind: "builtin",
        capabilities: &["lightflow.data.copy"],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::Passthrough,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.passthrough", "lightflow.data.copy")],
        plans_models: false,
        matcher: matches_passthrough,
    },
    ExecutorDefinition {
        id: PREVIEW_ENGINE,
        kind: "builtin",
        capabilities: &[IMAGE_GENERATE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::PreviewTextToImage,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[
            ("lightflow.atom.prompt", "lightflow.text.prompt"),
            ("lightflow.atom.preview_pixels", IMAGE_GENERATE_CAPABILITY),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: true,
        matcher: matches_preview_text_to_image,
    },
    ExecutorDefinition {
        id: PREVIEW_EDIT_ENGINE,
        kind: "builtin",
        capabilities: &[IMAGE_EDIT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::PreviewImageEdit,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[
            ("lightflow.atom.load_image", "lightflow.artifact.image"),
            ("lightflow.atom.preview_edit_pixels", IMAGE_EDIT_CAPABILITY),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: true,
        matcher: matches_preview_image_edit,
    },
    ExecutorDefinition {
        id: PREVIEW_INPAINT_ENGINE,
        kind: "builtin",
        capabilities: &[IMAGE_INPAINT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::PreviewInpaint,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[
            ("lightflow.atom.load_image", "lightflow.artifact.image"),
            ("lightflow.atom.load_mask", "lightflow.artifact.mask"),
            (
                "lightflow.atom.preview_inpaint_pixels",
                IMAGE_INPAINT_CAPABILITY,
            ),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: true,
        matcher: matches_preview_inpaint,
    },
];
