use super::super::{ExecutorAvailability, ExecutorDefinition};
use super::matchers::*;
use crate::api::plan::{
    DataPolicy, ExecutionRecipe, IMAGE_EDIT_CAPABILITY, IMAGE_GENERATE_CAPABILITY,
    IMAGE_INPAINT_CAPABILITY,
};

pub(super) static FLUX_EXECUTORS: [ExecutorDefinition; 5] = [
    ExecutorDefinition {
        id: "flux.runner.logical.v1",
        kind: "logical",
        capabilities: &[
            IMAGE_GENERATE_CAPABILITY,
            IMAGE_EDIT_CAPABILITY,
            IMAGE_INPAINT_CAPABILITY,
        ],
        features: &["flux"],
        env: None,
        command_env: None,
        visible: false,
        availability: ExecutorAvailability::Feature(cfg!(feature = "flux")),
        recipe: ExecutionRecipe::FluxTextToImage,
        data_policy: DataPolicy::DeviceResidentPreferred,
        atoms: &[
            ("lightflow.atom.load_flux_model", "lightflow.model.load"),
            ("lightflow.atom.load_text_encoder", "lightflow.model.load"),
            ("lightflow.atom.load_vae", "lightflow.model.load"),
            ("lightflow.atom.encode_prompt", "lightflow.text.encode"),
            ("lightflow.atom.sample_latents", IMAGE_GENERATE_CAPABILITY),
            ("lightflow.atom.decode_vae", "lightflow.image.decode"),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: true,
        matcher: matches_flux_text_to_image,
    },
    ExecutorDefinition {
        id: "flux.runner.logical.v1",
        kind: "logical",
        capabilities: &[IMAGE_EDIT_CAPABILITY],
        features: &["flux"],
        env: None,
        command_env: None,
        visible: false,
        availability: ExecutorAvailability::Feature(cfg!(feature = "flux")),
        recipe: ExecutionRecipe::FluxImageEdit,
        data_policy: DataPolicy::DeviceResidentPreferred,
        atoms: &[
            ("lightflow.atom.load_image", "lightflow.artifact.image"),
            ("lightflow.atom.load_flux_model", "lightflow.model.load"),
            ("lightflow.atom.load_text_encoder", "lightflow.model.load"),
            ("lightflow.atom.load_vae", "lightflow.model.load"),
            ("lightflow.atom.encode_prompt", "lightflow.text.encode"),
            ("lightflow.atom.sample_latents", IMAGE_EDIT_CAPABILITY),
            ("lightflow.atom.decode_vae", "lightflow.image.decode"),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: true,
        matcher: matches_flux_image_edit,
    },
    ExecutorDefinition {
        id: "flux.runner.logical.v1",
        kind: "logical",
        capabilities: &[IMAGE_INPAINT_CAPABILITY],
        features: &["flux"],
        env: None,
        command_env: None,
        visible: false,
        availability: ExecutorAvailability::Feature(cfg!(feature = "flux")),
        recipe: ExecutionRecipe::FluxInpaint,
        data_policy: DataPolicy::DeviceResidentPreferred,
        atoms: &[
            ("lightflow.atom.load_image", "lightflow.artifact.image"),
            ("lightflow.atom.load_mask", "lightflow.artifact.mask"),
            ("lightflow.atom.load_flux_model", "lightflow.model.load"),
            ("lightflow.atom.load_text_encoder", "lightflow.model.load"),
            ("lightflow.atom.load_vae", "lightflow.model.load"),
            ("lightflow.atom.encode_prompt", "lightflow.text.encode"),
            ("lightflow.atom.sample_latents", IMAGE_INPAINT_CAPABILITY),
            ("lightflow.atom.decode_vae", "lightflow.image.decode"),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: true,
        matcher: matches_flux_inpaint,
    },
    ExecutorDefinition {
        id: "lightflow.command.executor.v1",
        kind: "reserved",
        capabilities: &["lightflow.command"],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Unavailable,
        recipe: ExecutionRecipe::Passthrough,
        data_policy: DataPolicy::JsonValues,
        atoms: &[],
        plans_models: false,
        matcher: matches_never,
    },
    ExecutorDefinition {
        id: "lightflow.python.node.executor.v1",
        kind: "reserved",
        capabilities: &["lightflow.python.node"],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Unavailable,
        recipe: ExecutionRecipe::Passthrough,
        data_policy: DataPolicy::JsonValues,
        atoms: &[],
        plans_models: false,
        matcher: matches_never,
    },
];
