use super::super::{ExecutorAvailability, ExecutorDefinition};
use super::matchers::*;
use crate::api::plan::{
    DataPolicy, ExecutionRecipe, IMAGE_CROP_CAPABILITY, IMAGE_INVERT_CAPABILITY,
    IMAGE_LOAD_CAPABILITY, IMAGE_RESIZE_CAPABILITY, IMAGE_SAVE_CAPABILITY,
    IMAGE_UPSCALE_CAPABILITY, INVERT_ENGINE, MASK_COMPOSE_CAPABILITY,
};

pub(super) static IMAGE_EXECUTORS: [ExecutorDefinition; 7] = [
    ExecutorDefinition {
        id: INVERT_ENGINE,
        kind: "builtin",
        capabilities: &[IMAGE_INVERT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ImageInvert,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[
            ("lightflow.atom.load_image", "lightflow.artifact.image"),
            ("lightflow.atom.invert_pixels", IMAGE_INVERT_CAPABILITY),
            ("lightflow.atom.save_image", "lightflow.artifact.image"),
        ],
        plans_models: false,
        matcher: matches_image_invert,
    },
    ExecutorDefinition {
        id: "builtin.image.load.v1",
        kind: "builtin",
        capabilities: &[IMAGE_LOAD_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ImageLoad,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[("lightflow.atom.load_image", IMAGE_LOAD_CAPABILITY)],
        plans_models: false,
        matcher: matches_image_load,
    },
    ExecutorDefinition {
        id: "builtin.image.save.v1",
        kind: "builtin",
        capabilities: &[IMAGE_SAVE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ImageSave,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[("lightflow.atom.save_image", IMAGE_SAVE_CAPABILITY)],
        plans_models: false,
        matcher: matches_image_save,
    },
    ExecutorDefinition {
        id: "builtin.image.resize.v1",
        kind: "builtin",
        capabilities: &[IMAGE_RESIZE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ImageResize,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[("lightflow.atom.resize_pixels", IMAGE_RESIZE_CAPABILITY)],
        plans_models: false,
        matcher: matches_image_resize,
    },
    ExecutorDefinition {
        id: "builtin.image.crop.v1",
        kind: "builtin",
        capabilities: &[IMAGE_CROP_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ImageCrop,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[("lightflow.atom.crop_pixels", IMAGE_CROP_CAPABILITY)],
        plans_models: false,
        matcher: matches_image_crop,
    },
    ExecutorDefinition {
        id: "builtin.image.upscale.v1",
        kind: "builtin",
        capabilities: &[IMAGE_UPSCALE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::ImageUpscale,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[("lightflow.atom.upscale_pixels", IMAGE_UPSCALE_CAPABILITY)],
        plans_models: false,
        matcher: matches_image_upscale,
    },
    ExecutorDefinition {
        id: "builtin.mask.compose.v1",
        kind: "builtin",
        capabilities: &[MASK_COMPOSE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::MaskCompose,
        data_policy: DataPolicy::ArtifactHandles,
        atoms: &[("lightflow.atom.compose_masks", MASK_COMPOSE_CAPABILITY)],
        plans_models: false,
        matcher: matches_mask_compose,
    },
];
