use super::super::{ExecutorAvailability, ExecutorDefinition};
use super::matchers::*;
use crate::api::plan::{
    DataPolicy, ExecutionRecipe, FLUX_EXTERNAL_ENGINE, FLUX_NATIVE_ENGINE, IMAGE_EDIT_CAPABILITY,
    IMAGE_GENERATE_CAPABILITY, IMAGE_INPAINT_CAPABILITY, LLM_GENERATE_CAPABILITY, LLM_MOCK_ENGINE,
    TEXT_CONCAT_CAPABILITY, TEXT_REGEX_CAPABILITY, TEXT_TEMPLATE_CAPABILITY,
};

pub(super) static TEXT_LLM_EXECUTORS: [ExecutorDefinition; 7] = [
    ExecutorDefinition {
        id: LLM_MOCK_ENGINE,
        kind: "builtin",
        capabilities: &[LLM_GENERATE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::BuiltinLlmGenerate,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.mock_llm_generate", LLM_GENERATE_CAPABILITY)],
        plans_models: false,
        matcher: matches_builtin_llm_generate,
    },
    ExecutorDefinition {
        id: "rig-core",
        kind: "native",
        capabilities: &[LLM_GENERATE_CAPABILITY],
        features: &["rig"],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Feature(cfg!(feature = "rig")),
        recipe: ExecutionRecipe::RigLlmGenerate,
        data_policy: DataPolicy::JsonValues,
        atoms: &[
            (
                "lightflow.atom.select_llm_provider",
                "lightflow.llm.provider",
            ),
            ("lightflow.atom.build_rig_agent", LLM_GENERATE_CAPABILITY),
            ("lightflow.atom.prompt_llm", "lightflow.text.generate"),
        ],
        plans_models: true,
        matcher: matches_rig_llm,
    },
    ExecutorDefinition {
        id: "builtin.text.concat.v1",
        kind: "builtin",
        capabilities: &[TEXT_CONCAT_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::TextConcat,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.concat_text", TEXT_CONCAT_CAPABILITY)],
        plans_models: false,
        matcher: matches_text_concat,
    },
    ExecutorDefinition {
        id: "builtin.text.template.v1",
        kind: "builtin",
        capabilities: &[TEXT_TEMPLATE_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::TextTemplate,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.render_template", TEXT_TEMPLATE_CAPABILITY)],
        plans_models: false,
        matcher: matches_text_template,
    },
    ExecutorDefinition {
        id: "builtin.text.regex.v1",
        kind: "builtin",
        capabilities: &[TEXT_REGEX_CAPABILITY],
        features: &[],
        env: None,
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Always,
        recipe: ExecutionRecipe::TextRegex,
        data_policy: DataPolicy::JsonValues,
        atoms: &[("lightflow.atom.regex_text", TEXT_REGEX_CAPABILITY)],
        plans_models: false,
        matcher: matches_text_regex,
    },
    ExecutorDefinition {
        id: FLUX_EXTERNAL_ENGINE,
        kind: "external",
        capabilities: &[
            IMAGE_GENERATE_CAPABILITY,
            IMAGE_EDIT_CAPABILITY,
            IMAGE_INPAINT_CAPABILITY,
        ],
        features: &["flux"],
        env: Some("LIGHTFLOW_FLUX_RUNNER"),
        command_env: Some("LIGHTFLOW_FLUX_RUNNER"),
        visible: true,
        availability: ExecutorAvailability::FluxRunner,
        recipe: ExecutionRecipe::FluxTextToImage,
        data_policy: DataPolicy::DeviceResidentPreferred,
        atoms: &[],
        plans_models: true,
        matcher: matches_never,
    },
    ExecutorDefinition {
        id: FLUX_NATIVE_ENGINE,
        kind: "native",
        capabilities: &[
            IMAGE_GENERATE_CAPABILITY,
            IMAGE_EDIT_CAPABILITY,
            IMAGE_INPAINT_CAPABILITY,
        ],
        features: &["flux-native"],
        env: Some("LIGHTFLOW_FLUX_BACKEND"),
        command_env: None,
        visible: true,
        availability: ExecutorAvailability::Feature(cfg!(feature = "flux-native")),
        recipe: ExecutionRecipe::FluxTextToImage,
        data_policy: DataPolicy::DeviceResidentPreferred,
        atoms: &[],
        plans_models: true,
        matcher: matches_never,
    },
];
